// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvdJQl0JlQjS42ybEYfycMWdPZqr447lk',
    appId: '1:1075845010658:web:6b0bf62b8322ebd130fabb',
    messagingSenderId: '1075845010658',
    projectId: 'food-dash-52b17',
    authDomain: 'food-dash-52b17.firebaseapp.com',
    storageBucket: 'food-dash-52b17.appspot.com',
    measurementId: 'G-J0WMKBQWWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcU_FVjgCIOj2hQ0Q7etQFjiVwFMhBja4',
    appId: '1:1075845010658:android:d4ae5304cda1721c30fabb',
    messagingSenderId: '1075845010658',
    projectId: 'food-dash-52b17',
    storageBucket: 'food-dash-52b17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEbSsMGfnhgnUtdHcTWNprUQNHQlBZXt8',
    appId: '1:1075845010658:ios:77211d77c32df0b630fabb',
    messagingSenderId: '1075845010658',
    projectId: 'food-dash-52b17',
    storageBucket: 'food-dash-52b17.appspot.com',
    androidClientId: '1075845010658-2fhr4k73su162f6qg04qt8oor0ntepld.apps.googleusercontent.com',
    iosClientId: '1075845010658-hp5aoqgcffunr689mhhc6chk2bbiqbqf.apps.googleusercontent.com',
    iosBundleId: 'com.foodDelivery.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEbSsMGfnhgnUtdHcTWNprUQNHQlBZXt8',
    appId: '1:1075845010658:ios:f5a9d5391785105330fabb',
    messagingSenderId: '1075845010658',
    projectId: 'food-dash-52b17',
    storageBucket: 'food-dash-52b17.appspot.com',
    androidClientId: '1075845010658-2fhr4k73su162f6qg04qt8oor0ntepld.apps.googleusercontent.com',
    iosClientId: '1075845010658-9dp5r3hod9it971dtmlf6mocv8mmaa8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvdJQl0JlQjS42ybEYfycMWdPZqr447lk',
    appId: '1:1075845010658:web:27913fa3edbfe59130fabb',
    messagingSenderId: '1075845010658',
    projectId: 'food-dash-52b17',
    authDomain: 'food-dash-52b17.firebaseapp.com',
    storageBucket: 'food-dash-52b17.appspot.com',
    measurementId: 'G-VV6GKEL26Z',
  );
}
